# https://stackoverflow.com/questions/69112842/how-can-i-allow-github-automerge-to-perform-the-merge-without-explicitly-enablin
# 코드 리뷰를 완료하면 자동으로 Merge됨

on:
  pull_request:
    branches:
      - main

jobs:
  enable-automerge:
    name: Auto enable auto merge
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{GITHUB_TOKEN}}
